### PR TITLE
 Load favicon from website, fixes #55

### LINKED ISSUE #55: Load favicon from webpage and display in front of URL
Would be a nifty addition.

### PR DESCRIPTION
**Pull request by mortenn**
Also fixes broken loading window

### CODE REVIEW

**Comment by LB--** [comment]
It's not obvious from the source here, but can this be disabled with a setting? It's a bit of a privacy issue since normally this app would stop unexpected internet connections being made.

**Comment by mortenn** [comment]
Yes, this feature respects the "disable network traffic" option which is already there

**Comment by mortenn** [comment]
I am not entirely happy with the state of this feature though, there are some complications with favicons these days it seems, it's not as simple and easy as it once were :p

**Comment by mortenn** [comment]
as for privacy concerns, maybe add another setting which defaults to true and only loads favicons from known sites? preconfigured defaults, say?

maybe you'll open an issue to track all this @LB-- ?

**Comment by LB--** [comment]
The existing setting sounds good enough to me, I'm not sure it needs to be more complicated than that

**Pull request merged**
