### PR TITLE
Add validation on input, fix prefix rule, allow moving windows, show within Windows Start

### PR DESCRIPTION
**Pull request by daltskin**
Fix bug #35

### CODE REVIEW

**Comment by daltskin** [comment]
Also fixes #37

**Comment by daltskin** [comment]
Fix #38 - allow window and sub-window to be moved around the screen or to a different screen

image

**Comment by daltskin** [comment]
Address  #39 - Add Browser Picker to Windows Start Menu :)

image

**Comment by mortenn** [comment]
Thanks!

**Pull request merged**
